import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import Provider from "./_trpc/Provider";

import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const calSans = localFont({
  src: "../public/fonts/CalSans-SemiBold.otf",
  variable: "--font-cal-sans",
});

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(calSans.variable, inter.variable, "bg-neutral-50")}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
